rpm-sequoia: Use DEBUG_BUILD to determine build directory
Debug builds fail with a panic in build.rs when attempting
to create rpm-sequoia.pc in a non-existent target/debug directory:

process didn't exit successfully: `TOPDIR/tmp/work/core2-32-wrs-linux/rpm-sequoia/1.7.0/build/target/debug/build/rpm-sequoia-d2609670a855c0b5/build-script-build` (exit status: 101)
— stderr
thread 'main' panicked at build.rs:125:36:
Creating "TOPDIR/tmp/work/core2-32-wrs-linux/rpm-sequoia/1.7.0/sources-unpack/git/target/debug/rpm-sequoia.pc" (CARGO_TARGET_DIR: None): Os
{ code: 2, kind: NotFound, message: "No such file or directory" }

This was caused by the build and install logic assuming a fixed release directory
in rpm-sequoia recipe.

Update build and install steps to use the ${BUILD_DIR} variable,
which is set based on the value of DEBUG_BUILD from cargo.bbclass.
(rpm-sequoia inherits cargo)
This ensures paths used for rpm-sequoia.pc generation and installation
are valid in both debug and release configurations.

(From OE-Core rev: 80d9c71278903a4d9f8aae49a72dd00aee69b138)

Signed-off-by: Yash Shinde <Yash.Shinde@windriver.com>
Signed-off-by: Antonin Godard <antonin.godard@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>